pipeline:
  name: remote-pipe
  identifier: remotepipe
  projectIdentifier: V
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo hi
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps: []
          services:
            values:
              - serviceRef: docker2
                serviceInputs:
                  serviceDefinition:
                    type: Kubernetes
                    spec:
                      artifacts:
                        primary:
                          primaryArtifactRef: s1
                          sources:
                            - identifier: s1
                              type: DockerRegistry
                              spec:
                                tag: <+input>
                                digest: <+input>
                gitBranch: gitx-commit
            metadata:
              parallel: true
          environments:
            metadata:
              parallel: true
            values:
              - environmentRef: env2
                gitBranch: gitx-commit
                deployToAll: false
                infrastructureDefinitions:
                  - identifier: infra123
              - environmentRef: envremote
                gitBranch: hello
                deployToAll: true
                infrastructureDefinitions: <+input>
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
